### ISSUE TITLE
Website TOC resize handle broken

### ISSUE THREAD

**Issue by WebMechanic** [stevage/map-gl-utils#32]
Hello,

if I grab the drag handler between TOC and content parts to get some space for the content itself w/o the need to scroll horizontally, the handler sticks to the mouse and can no longer be released: click, dblclick, esc -- all do nothing. 
That's on Chrome 95 for Win10 with a vanilla mouse.

I have to reload the page and face a screen-estate wasting TOC panel and scroll the content part. Yes, I don't have a HD monitor :-)

May I suggest to reduce the overall width of the left TOC **anyway**? It's way to large for the short lines present in the TOC wasting alot of horizontal space.

Thanks.

**Comment by WebMechanic** [comment]
here's an idea:
```css
/* the container which oddly enough has no id nor is it <main> */
div.flex {
  --toc: 20vw;
  --gap: 10px;
}
.gutter-horizontal {
  flex-basis: calc(var(--gap) * 2)
}
#split-left {
  flex-basis: calc(var(--toc) - 10px)
}
#split-right {
  flex-basis: calc(100vw - var(--toc) - 10px)
}
```

then your slit-dragging script could just change the `--toc` variable and let the browser do its job.

Enjoy!
